# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'ShopSDKIntegrationApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'sonect-shop-sdk-ios'
  pod 'sonect-scandit-scan-plugin'
  pod 'sonect-google-address-autocompletion-plugin'

end
